development:
  adapter: postgresql
  encoding: unicode
  database: refills_on_rails_development
  pool: 5
  username: VajraCreations
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: refills_on_rails_test
  pool: 5
  username: VajraCreations
  password: