# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

#---------------
# THIS IS A DEMO APP SO I AM LEAVING THE SECRET KEY HERE BUT... (read the following) #
#---------------

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7af0f7f61b3378bf61d344871d2d75b2b04a8540afd050c20c8b8c82d2c0472c364cac70b2d3a4db8cdd9f7bdd356365d317421b747fb3645f2664fcebbbb1a

test:
  secret_key_base: 313887782fb36b28adc48e773982b6a695eab21c76f7c1ad9d82d63cf3b8ea1b25f74368abb34f6e1450e34d8cf0effeddc20319b44fda75c1a3eb6dcf3e3a3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
